### ISSUE TITLE
Error when executing Slack command

### ISSUE THREAD

**Issue by poyyaren** [IBM-Bluemix/openwhisk-slackapp#15]
Setup and registration seemed to work. When I execute the Slack command it fails with the error "http_client_error". From the "bx wsk activation poll" I see the following error:

>    "2020-05-30T21:45:09.880602Z    stderr: { Error: Cannot find module 'cloudant'",
>     "2020-05-30T21:45:09.880608Z    stderr: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)",
>     "2020-05-30T21:45:09.880610Z    stderr: at Function.Module._load (internal/modules/cjs/loader.js:562:25)",
>     "2020-05-30T21:45:09.880613Z    stderr: at Module.require (internal/modules/cjs/loader.js:692:17)",
>     "2020-05-30T21:45:09.880615Z    stderr: at require (internal/modules/cjs/helpers.js:25:18)",
>     "2020-05-30T21:45:09.880618Z    stderr: at NodeActionRunner.main [as userScriptMain] (eval at initializeActionHandler (/nodejsAction/runner.js:57:23), <anonymous>:59:18)",
>     "2020-05-30T21:45:09.880621Z    stderr: at Promise (/nodejsAction/runner.js:73:35)",
>     "2020-05-30T21:45:09.880623Z    stderr: at new Promise (<anonymous>)",
>     "2020-05-30T21:45:09.880626Z    stderr: at NodeActionRunner.run (/nodejsAction/runner.js:71:16)",
>     "2020-05-30T21:45:09.880629Z    stderr: at doRun (/nodejsAction/src/service.js:196:14)",
>     "2020-05-30T21:45:09.880636Z    stderr: at runCode (/nodejsAction/src/service.js:141:20) code: 'MODULE_NOT_FOUND' }",
>     "2020-05-30T21:45:09.882Z       stderr: The action did not initialize or run as expected. Log data might be missing."

Did I do something wrong during setup?

**Comment by l2fprod** [comment]
updated to latest cloudant
